version: '3.9'

services:
  db:
    image: postgres:13
    container_name: cocktails-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cocktails

  db_test:
    image: postgres:13
    container_name: cocktails-db-testing
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_DB}
    ports:
      - '5434:5432'
    volumes:
      - postgres_test:/var/lib/postgresql/data
    networks:
      - cocktails

  # redis:
  #   container_name: cocktails-redis
  #   image: redis:latest
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis:/data
  #   networks:
  #     - cocktails

  api:
    image: api
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@192.168.32.3:5432/${POSTGRES_DB}?schema=public
    ports:
      - '8081:3333'
    depends_on:
      - db

  # client:
  #   image: html
  #   environment:
  #     - apiPath=http://api:3333
  #   ports:
  #     - '8080:3334'

networks:
  cocktails:

volumes:
  postgres:
  postgres_test:
  redis:
