version: '3.9'

services:
  db:
    image: postgres:13
    container_name: prisma-cocktails-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cocktails

  db_test:
    image: postgres:13
    container_name: prisma-cocktails-db-testing
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cocktails

  redis:
    container_name: primsa-cocktails-redis
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - cocktails

  api:
    container_name: primsa-cocktails-api
    build: .
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_HOST: redis
    depends_on:
      - db
    networks:
      - cocktails

networks:
  cocktails:

volumes:
  postgres_data:
  postgres_test_data:
  redis_data:
