version: '3.9'

services:
  db:
    image: postgres:13
    container_name: cocktails-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cocktails

  db_test:
    image: postgres:13
    container_name: cocktails-db-testing
    env_file:
      - .env
      # - .env.test this seems to be ignored in favor of the .env file
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: cocktails-test
    ports:
      - '5434:5432'
    volumes:
      - postgres_test:/var/lib/postgresql/data
    networks:
      - cocktails

  api:
    image: api
    environment:
      DATABASE_URL: postgresql://tylerbauman:password@db:5432/cocktails?schema=public
    ports:
      - '3333:3333'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cocktails

networks:
  cocktails:


volumes:
  postgres:
  postgres_test:
