version: '3.9'

services:
  db:
    image: postgres:13
    container_name: cocktails-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - cocktails

  db_test:
    image: postgres:13
    container_name: cocktails-db-testing
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_DB}
    ports:
      - '5434:5432'
    volumes:
      - postgres_test:/var/lib/postgresql/data
    networks:
      - cocktails

  api:
    image: api
    environment:
      DATABASE_URL: postgresql://tylerbauman:password@localhost:5432/cocktails?schema=public
    ports:
      - '3333:3333'
    depends_on:
      - db
    networks:
      - cocktails

networks:
  cocktails:

volumes:
  postgres:
  postgres_test:
