name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cocktails-ci
          PGDATA: /data/postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - run: |
          echo ${{ env.TEST_DATABASE_URL }}

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm install nx
          npm ci

      - name: Run API tests
        env:
          TEST_DATABASE_URL: 'postgresql://tylerbauman:password@postgres:${{ job.services.postgres.ports[5432] }}/cocktails-ci?schema=public'
        run: NODE_ENV=test npx nx run api:test --coverage --verbose

      - name: Upload api coverage reports to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: api
          files: ./coverage/apps/api/coverage-final.json

      - name: Run Client tests
        run: npx nx run client:test --coverage --verbose

      - name: Upload client coverage reports to codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: client
          files: ./coverage/apps/client/coverage-final.json
